#!/bin/bash

EXEC_LLVMCOV=llvm-cov

LLVM_VERSION=$($EXEC_LLVMCOV -version | grep -i "LLVM version" \
    | sed "s/^\([A-Za-z ]*\)\([0-9]\).\([0-9]\).*$/\2.\3/g")

if [ "$1" = "-v" ] ; then
  echo "llvm-cov-wrapper $LLVM_VERSION"
  exit 0
fi

if [ -n "$LLVM_VERSION" ] ; then
    MAJOR=$(echo $LLVM_VERSION | cut -d'.' -f1)
    MINOR=$(echo $LLVM_VERSION | cut -d'.' -f2)

    if [ $MAJOR -eq 3 ] && [ $MINOR -le 4 ] ; then
        if [ -f "$1" ] ; then
            filename=$(basename "$1")
            extension="${filename##*.}"

            case "$extension" in
                "gcno") exec $EXEC_LLVMCOV --gcno="$1" ;;
                "gcda") exec $EXEC_LLVMCOV --gcda="$1" ;;
            esac
        fi
    fi

    if [ $MAJOR -eq 3 ] && [ $MINOR -le 5 ] ; then
        exec $EXEC_LLVMCOV $@
    fi
fi

exec $EXEC_LLVMCOV gcov $@

